# Generated by Django 3.1.5 on 2021-02-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210131_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('articles', models.ManyToManyField(to='articles.Article')),
            ],
        ),
    ]
