# Generated by Django 3.1.5 on 2021-02-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='someUglyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Group',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='group_id',
            new_name='section_id',
        ),
    ]
