# Generated by Django 3.1.5 on 2021-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210204_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(blank=True, to='articles.Article'),
        ),
    ]
