# Generated by Django 3.1.6 on 2021-02-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210206_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
