# Generated by Django 3.1.6 on 2021-02-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210213_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section_id',
            new_name='id',
        ),
    ]
