# Generated by Django 3.1.6 on 2021-03-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20210217_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='articles/default.png', upload_to='covers'),
        ),
    ]
