# Generated by Django 3.1.6 on 2021-03-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20210311_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
    ]
