# Generated by Django 3.1.6 on 2021-03-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_remove_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='covers/default.png', upload_to='covers/'),
        ),
    ]
