# Generated by Django 3.1.6 on 2021-02-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_logrecord_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrecord',
            name='test',
        ),
    ]
