# Generated by Django 3.1.6 on 2021-02-25 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_remove_logrecord_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecord',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
