# Generated by Django 3.1.6 on 2021-02-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_logrecord_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrecord',
            name='created',
        ),
    ]
